const AnotherComponent = () => {
  return (
    <>
      <div>PAGE ONE</div>
      <div>PAGE ONE</div>
      <div>PAGE ONE</div>
      <div>PAGE ONE</div>
      <div>PAGE ONE</div>
      <div>PAGE ONE</div>
      <div>PAGE ONE</div>
      <div>PAGE ONE</div>
      <div>PAGE ONE</div>
      <div>PAGE ONE</div>
      <div>PAGE ONE</div>
      <div>PAGE ONE</div>
      <div>PAGE ONE</div>
      <div>PAGE ONE</div>
      <div>PAGE ONE</div>
      <div>PAGE ONE</div>
      <div>PAGE ONE</div>
      <div>PAGE ONE</div>
      <div>PAGE ONE</div>
      <div>PAGE ONE</div> <div>PAGE ONE</div>
      <div>PAGE ONE</div>
      <div>PAGE ONE</div>
      <div>PAGE ONE</div>
      <div>PAGE ONE</div>
      <div>PAGE ONE</div>
      <div>PAGE ONE</div>
      <div>PAGE ONE</div>
      <div>PAGE ONE</div>
      <div>PAGE ONE</div>
      <div>PAGE ONE</div>
      <div>PAGE ONE</div>
      <div>PAGE ONE</div>
      <div>PAGE ONE</div>
      <div>PAGE ONE</div>
      <div>PAGE ONE</div>
      <div>PAGE ONE</div>
      <div>PAGE ONE</div>
      <div>PAGE ONE</div>
      <div>PAGE ONE</div> <div>PAGE ONE</div>
      <div>PAGE ONE</div>
      <div>PAGE ONE</div>
      <div>PAGE ONE</div>
      <div>PAGE ONE</div>
      <div>PAGE ONE</div>
      <div>PAGE ONE</div>
      <div>PAGE ONE</div>
      <div>PAGE ONE</div>
      <div>PAGE ONE</div>
      <div>PAGE ONE</div>
      <div>PAGE ONE</div>
      <div>PAGE ONE</div>
      <div>PAGE ONE</div>
      <div>PAGE ONE</div>
      <div>PAGE ONE</div>
      <div>PAGE ONE</div>
      <div>PAGE ONE</div>
      <div>PAGE ONE</div>
      <div>PAGE ONE</div> <div>PAGE ONE</div>
      <div>PAGE ONE</div>
      <div>PAGE ONE</div>
      <div>PAGE ONE</div>
      <div>PAGE ONE</div>
      <div>PAGE ONE</div>
      <div>PAGE ONE</div>
      <div>PAGE ONE</div>
      <div>PAGE ONE</div>
      <div>PAGE ONE</div>
      <div>PAGE ONE</div>
      <div>PAGE ONE</div>
      <div>PAGE ONE</div>
      <div>PAGE ONE</div>
      <div>PAGE ONE</div>
      <div>PAGE ONE</div>
      <div>PAGE ONE</div>
      <div>PAGE ONE</div>
      <div>PAGE ONE</div>
      <div>PAGE ONE</div> <div>PAGE ONE</div>
      <div>PAGE ONE</div>
      <div>PAGE ONE</div>
      <div>PAGE ONE</div>
      <div>PAGE ONE</div>
      <div>PAGE ONE</div>
      <div>PAGE ONE</div>
      <div>PAGE ONE</div>
      <div>PAGE ONE</div>
      <div>PAGE ONE</div>
      <div>PAGE ONE</div>
      <div>PAGE ONE</div>
      <div>PAGE ONE</div>
      <div>PAGE ONE</div>
      <div>PAGE ONE</div>
      <div>PAGE ONE</div>
      <div>PAGE ONE</div>
      <div>PAGE ONE</div>
      <div>PAGE ONE</div>
      <div>PAGE ONE</div>
      <div>PAGE ONE</div>
      <div>PAGE ONE</div>
      <div>PAGE ONE</div>
      <div>PAGE ONE</div>
      <div>PAGE ONE</div>
      <div>PAGE ONE</div>
      <div>PAGE ONE</div>
      <div>PAGE ONE</div>
      <div>PAGE ONE</div>
      <div>PAGE ONE</div>
      <div>PAGE ONE</div>
      <div>PAGE ONE</div>
      <div>PAGE ONE</div>
      <div>PAGE ONE</div>
      <div>PAGE ONE</div>
      <div>PAGE ONE</div> <div>PAGE ONE</div>
      <div>PAGE ONE</div>
      <div>PAGE ONE</div>
      <div>PAGE ONE</div>
      <div>PAGE ONE</div>
      <div>PAGE ONE</div>
      <div>PAGE ONE</div>
      <div>PAGE ONE</div>
      <div>PAGE ONE</div>
      <div>PAGE ONE</div>
      <div>PAGE ONE</div>
      <div>PAGE ONE</div>
      <div>PAGE ONE</div>
      <div>PAGE ONE</div>
      <div>PAGE ONE</div>
      <div>PAGE ONE</div>
      <div>PAGE ONE</div>
      <div>PAGE ONE</div>
      <div>PAGE ONE</div>
      <div>PAGE ONE</div> <div>PAGE ONE</div>
      <div>PAGE ONE</div>
      <div>PAGE ONE</div>
      <div>PAGE ONE</div>
      <div>PAGE ONE</div>
      <div>PAGE ONE</div>
      <div>PAGE ONE</div>
      <div>PAGE ONE</div>
      <div>PAGE ONE</div>
      <div>PAGE ONE</div>
      <div>PAGE ONE</div>
      <div>PAGE ONE</div>
      <div>PAGE ONE</div>
      <div>PAGE ONE</div>
      <div>PAGE ONE</div>
      <div>PAGE ONE</div>
      <div>PAGE ONE</div>
      <div>PAGE ONE</div>
      <div>PAGE ONE</div>
      <div>PAGE ONE</div> <div>PAGE ONE</div>
      <div>PAGE ONE</div>
      <div>PAGE ONE</div>
      <div>PAGE ONE</div>
      <div>PAGE ONE</div>
      <div>PAGE ONE</div>
      <div>PAGE ONE</div>
      <div>PAGE ONE</div>
      <div>PAGE ONE</div>
      <div>PAGE ONE</div>
      <div>PAGE ONE</div>
      <div>PAGE ONE</div>
      <div>PAGE ONE</div>
      <div>PAGE ONE</div>
      <div>PAGE ONE</div>
      <div>PAGE ONE</div>
      <div>PAGE ONE</div>
      <div>PAGE ONE</div>
      <div>PAGE ONE</div>
      <div>PAGE ONE</div> <div>PAGE ONE</div>
      <div>PAGE ONE</div>
      <div>PAGE ONE</div>
      <div>PAGE ONE</div>
      <div>PAGE ONE</div>
      <div>PAGE ONE</div>
      <div>PAGE ONE</div>
      <div>PAGE ONE</div>
      <div>PAGE ONE</div>
      <div>PAGE ONE</div>
      <div>PAGE ONE</div>
      <div>PAGE ONE</div>
      <div>PAGE ONE</div>
      <div>PAGE ONE</div>
      <div>PAGE ONE</div>
      <div>PAGE ONE</div>
      <div>PAGE ONE</div>
      <div>PAGE ONE</div>
      <div>PAGE ONE</div>
      <div>PAGE ONE</div>
      <div>PAGE ONE</div>
    </>
  );
};

export default AnotherComponent;
