import AnotherBody from "./AnotherBody";
import AnotherPage from "./AnotherPage";
import AnotherComponent from "./AnotherComponent";

const LotsOfLinesComp = () => {
  const hasAnother = true;
  const hasBody = true;

  return (
    <>
      <div>WELCOME!</div>
      {hasBody && <AnotherComponent />}
      <div>WELCOME!</div>
      <div>WELCOME!</div>
      <div>WELCOME!</div>
      <div>WELCOME!</div>
      <div>WELCOME!</div>
      <div>WELCOME!</div>
      <div>WELCOME!</div>
      <div>WELCOME!</div>
      <div>WELCOME!</div>
      <div>WELCOME!</div>
      <div>WELCOME!</div>
      <div>WELCOME!</div>
      <div>WELCOME!</div>
      <div>WELCOME!</div>
      <div>WELCOME!</div>
      <div>WELCOME!</div>
      <div>WELCOME!</div>
      <div>WELCOME!</div>
      <div>WELCOME!</div>
      <div>WELCOME!</div>
      <div>WELCOME!</div>
      <div>WELCOME!</div>
      <div>WELCOME!</div>
      <div>WELCOME!</div>
      <div>WELCOME!</div>
      <div>WELCOME!</div>
      <div>WELCOME!</div>
      <div>WELCOME!</div>
      <div>WELCOME!</div>
      <div>WELCOME!</div>
      <div>WELCOME!</div>
      <div>WELCOME!</div>
      <div>WELCOME!</div>
      <div>WELCOME!</div>
      <div>WELCOME!</div>
      <div>WELCOME!</div>
      <div>WELCOME!</div>
      <div>WELCOME!</div>
      <div>WELCOME!</div>
      <div>WELCOME!</div>
      <div>WELCOME!</div>
      <div>WELCOME!</div>
      <div>WELCOME!</div>
      <div>WELCOME!</div>
      <div>WELCOME!</div>
      <div>WELCOME!</div>
      <div>WELCOME!</div>
      <div>WELCOME!</div>
      <div>WELCOME!</div>
      <div>WELCOME!</div>
      <div>WELCOME!</div>
      <div>WELCOME!</div>
      <div>WELCOME!</div>
      <div>WELCOME!</div>
      <div>WELCOME!</div>
      <div>WELCOME!</div>
      <div>WELCOME!</div>
      <div>WELCOME!</div>
      <div>WELCOME!</div>
      <div>WELCOME!</div>
      <div>WELCOME!</div>
      <div>WELCOME!</div>
      <div>WELCOME!</div>
      <div>WELCOME!</div>
      <div>WELCOME!</div>
      <div>WELCOME!</div>
      <div>WELCOME!</div>
      <div>WELCOME!</div>
      <div>WELCOME!</div>
      <div>WELCOME!</div>
      <div>WELCOME!</div>
      <div>WELCOME!</div>
      <div>WELCOME!</div>
      <div>WELCOME!</div>
      <div>WELCOME!</div>
      <div>WELCOME!</div>
      <div>WELCOME!</div>
      <div>WELCOME!</div>
      <div>WELCOME!</div>
      <div>WELCOME!</div>
      <div>WELCOME!</div>
      <div>WELCOME!</div>
      <div>WELCOME!</div>
      <div>WELCOME!</div>
      <div>WELCOME!</div>
      <div>WELCOME!</div>
      <div>WELCOME!</div>
      <div>WELCOME!</div>
      <div>WELCOME!</div>
      <div>WELCOME!</div>
      <div>WELCOME!</div>
      <div>WELCOME!</div>
      <div>WELCOME!</div>
      <div>WELCOME!</div>
      <div>WELCOME!</div>
      <div>WELCOME!</div>
      <div>WELCOME!</div>
      <div>WELCOME!</div>
      <div>WELCOME!</div>
      <div>WELCOME!</div>
      <div>WELCOME!</div>
      <div>WELCOME!</div>
      <div>WELCOME!</div>
      <div>WELCOME!</div>
      <div>WELCOME!</div>
      <div>WELCOME!</div>
      <div>WELCOME!</div>
      <div>WELCOME!</div>
      <div>WELCOME!</div>
      <div>WELCOME!</div>
      <div>WELCOME!</div>
      <div>WELCOME!</div>
      <div>WELCOME!</div>
      <div>WELCOME!</div>
      <div>WELCOME!</div>
      <div>WELCOME!</div>
      <div>WELCOME!</div>
      <div>WELCOME!</div>
      <div>WELCOME!</div>
      <div>WELCOME!</div>
      <div>WELCOME!</div>
      <div>WELCOME!</div>
      <div>WELCOME!</div>
      <div>WELCOME!</div>
      <div>WELCOME!</div>
      <div>WELCOME!</div>
      <div>WELCOME!</div>
      <div>WELCOME!</div>
      <div>WELCOME!</div>
      <div>WELCOME!</div>
      <div>WELCOME!</div>
      <div>WELCOME!</div>
      <div>WELCOME!</div>
      <div>WELCOME!</div>
      <div>WELCOME!</div>
      <div>WELCOME!</div>
      <div>WELCOME!</div>
      {hasAnother ? <AnotherPage /> : "sa"}
      <AnotherBody />
    </>
  );
};

export default LotsOfLinesComp;
