const Page = () => {
  return (
    <>
      <div>Page!</div>
      <div>Page!</div>
      <div>Page!</div>
      <div>Page!</div>
      <div>Page!</div>
      <div>Page!</div>
      <div>Page!</div>
      <div>Page!</div>
      <div>Page!</div>
      <div>Page!</div>
      <div>Page!</div>
      <div>Page!</div>
      <div>Page!</div>
      <div>Page!</div>
      <div>Page!</div>
      <div>Page!</div>
      <div>Page!</div>
      <div>Page!</div>
      <div>Page!</div>
      <div>Page!</div>
      <div>Page!</div>
      <div>Page!</div>
      <div>Page!</div>
      <div>Page!</div>
      <div>Page!</div>
      <div>Page!</div>
      <div>Page!</div>
      <div>Page!</div>
      <div>Page!</div>
      <div>Page!</div>
      <div>Page!</div>
      <div>Page!</div>
      <div>Page!</div>
      <div>Page!</div>
      <div>Page!</div>
      <div>Page!</div>
      <div>Page!</div>
      <div>Page!</div>
      <div>Page!</div>
      <div>Page!</div>
      <div>Page!</div>
      <div>Page!</div>
      <div>Page!</div>
      <div>Page!</div>
      <div>Page!</div>
      <div>Page!</div>
    </>
  );
};

export default Page;
