export default function RenderedThroughIf() {
  return (
    <>
      <div>WELCOME!</div>
      <div>WELCOME!</div>
      <div>WELCOME!</div>
      <div>WELCOME!</div>
      <div>WELCOME!</div>
      <div>WELCOME!</div>
      <div>WELCOME!</div>
      <div>WELCOME!</div>
      <div>WELCOME!</div>
      <div>WELCOME!</div>
      <div>WELCOME!</div>
      <div>WELCOME!</div>
      <div>WELCOME!</div>
      <div>WELCOME!</div>
      <div>WELCOME!</div>
      <div>WELCOME!</div>
      <div>WELCOME!</div>
      <div>WELCOME!</div>
      <div>WELCOME!</div>
      <div>WELCOME!</div>
      <div>WELCOME!</div>
      <div>WELCOME!</div>
      <div>WELCOME!</div>
      <div>WELCOME!</div>
      <div>WELCOME!</div>
      <div>WELCOME!</div>
      <div>WELCOME!</div>
      <div>WELCOME!</div>
      <div>WELCOME!</div>
      <div>WELCOME!</div>
      <div>WELCOME!</div>
      <div>WELCOME!</div>
      <div>WELCOME!</div>
      <div>WELCOME!</div>
      <div>WELCOME!</div>
      <div>WELCOME!</div>
      <div>WELCOME!</div>
      <div>WELCOME!</div>
      <div>WELCOME!</div>
      <div>WELCOME!</div>
      <div>WELCOME!</div>
      <div>WELCOME!</div>
      <div>WELCOME!</div>
      <div>WELCOME!</div>
      <div>WELCOME!</div>
      <div>WELCOME!</div>
      <div>WELCOME!</div>
      <div>WELCOME!</div>
      <div>WELCOME!</div>
      <div>WELCOME!</div>
      <div>WELCOME!</div>
      <div>WELCOME!</div>
      <div>WELCOME!</div>
      <div>WELCOME!</div>
      <div>WELCOME!</div>
      <div>WELCOME!</div>
      <div>WELCOME!</div>
      <div>WELCOME!</div>
      <div>WELCOME!</div>
      <div>WELCOME!</div>
      <div>WELCOME!</div>
      <div>WELCOME!</div>
    </>
  );
}
